export const CITIES_BY_PROVINCE: Record<string, string[]> = {
  'Buenos Aires': [
    'Abasto',
    'Adolfo Alsina',
    'Adolfo Gonzales Chaves',
    'Aguas Verdes',
    'Alberti',
    'Alejandro Korn',
    'Almirante Brown',
    'Alta Gracia',
    'Arrecifes',
    'Arroyo Seco',
    'Azul',
    'Bahía Blanca',
    'Balcarce',
    'Baradero',
    'Barker',
    'Batán',
    'Benito Juárez',
    'Berazategui',
    'Berisso',
    'Bolívar',
    'Bragado',
    'Brandsen',
    'Burzaco',
    'Campana',
    'Cañuelas',
    'Cariló',
    'Carmen de Areco',
    'Carmen de Patagones',
    'Castelli',
    'Castelar',
    'Chascomús',
    'Chivilcoy',
    'Claromecó',
    'Coronel Dorrego',
    'Coronel Pringles',
    'Coronel Rosales',
    'Coronel Suárez',
    'Darregueira',
    'Del Viso',
    'Dolores',
    'Don Torcuato',
    'El Palomar',
    'Ensenada',
    'Escobar',
    'Esquel',
    'Exaltación de la Cruz',
    'Ezeiza',
    'Florencio Varela',
    'Florentino Ameghino',
    'General Arenales',
    'General Belgrano',
    'General Guido',
    'General Juan Madariaga',
    'General La Madrid',
    'General Las Heras',
    'General Lavalle',
    'General Paz',
    'General Pinto',
    'General Pueyrredón',
    'General Rodríguez',
    'General San Martín',
    'General Villegas',
    'Glew',
    'Gonzales Chaves',
    'Guaminí',
    'Hipólito Yrigoyen',
    'Hurlingham',
    'Ituzaingó',
    'José C. Paz',
    'Junín',
    'La Plata',
    'La Reja',
    'Laprida',
    'Las Flores',
    'Leandro N. Alem',
    'Lincoln',
    'Lobería',
    'Lobos',
    'Lomas de Zamora',
    'Longchamps',
    'Luján',
    'Magdalena',
    'Maipú',
    'Malvinas Argentinas',
    'Mar Chiquita',
    'Mar de Ajó',
    'Mar del Plata',
    'Mar del Tuyú',
    'Marcos Paz',
    'Mercedes',
    'Merlo',
    'Miramar',
    'Monte',
    'Monte Hermoso',
    'Moreno',
    'Morón',
    'Navarro',
    'Necochea',
    'Nueve de Julio',
    'Olavarría',
    'Patagones',
    'Pehuajó',
    'Pellegrini',
    'Pergamino',
    'Pila',
    'Pilar',
    'Pinamar',
    'Presidente Perón',
    'Puan',
    'Punta Indio',
    'Quilmes',
    'Ramallo',
    'Rauch',
    'Rivadavia',
    'Rojas',
    'Roque Pérez',
    'Saavedra',
    'Saladillo',
    'Salliqueló',
    'Salto',
    'San Andrés de Giles',
    'San Antonio de Areco',
    'San Bernardo',
    'San Cayetano',
    'San Fernando',
    'San Isidro',
    'San Miguel',
    'San Miguel del Monte',
    'San Nicolás',
    'San Pedro',
    'San Vicente',
    'Santa Teresita',
    'Suipacha',
    'Tandil',
    'Tapalqué',
    'Tigre',
    'Tordillo',
    'Tornquist',
    'Trenque Lauquen',
    'Tres Arroyos',
    'Tres Lomas',
    'Tres de Febrero',
    'Veinticinco de Mayo',
    'Vicente López',
    'Villa Gesell',
    'Villarino',
    'Zárate',
  ],

  'CABA': [
    'Agronomía',
    'Almagro',
    'Balvanera',
    'Barracas',
    'Belgrano',
    'Boedo',
    'Caballito',
    'Chacarita',
    'Coghlan',
    'Colegiales',
    'Constitución',
    'Flores',
    'Floresta',
    'La Boca',
    'La Paternal',
    'Las Cañitas',
    'Liniers',
    'Mataderos',
    'Microcentro',
    'Monte Castro',
    'Montserrat',
    'Nueva Pompeya',
    'Núñez',
    'Palermo',
    'Palermo Chico',
    'Palermo Hollywood',
    'Palermo Soho',
    'Parque Avellaneda',
    'Parque Chacabuco',
    'Parque Chas',
    'Parque Patricios',
    'Puerto Madero',
    'Recoleta',
    'Retiro',
    'Saavedra',
    'San Cristóbal',
    'San Nicolás',
    'San Telmo',
    'Vélez Sársfield',
    'Versalles',
    'Villa Crespo',
    'Villa Ortúzar',
    'Villa Pueyrredón',
    'Villa Real',
    'Villa Riachuelo',
    'Villa Santa Rita',
    'Villa Soldati',
    'Villa Urquiza',
    'Villa del Parque',
    'Villa Devoto',
    'Villa General Mitre',
    'Villa Lugano',
    'Villa Luro',
  ],

  'Córdoba': [
    'Adelia María',
    'Almafuerte',
    'Alta Gracia',
    'Arroyito',
    'Bell Ville',
    'Berrotarán',
    'Brinkmann',
    'Calamuchita',
    'Camilo Aldao',
    'Capilla del Monte',
    'Carlos Paz',
    'Carrilobo',
    'Cintra',
    'Córdoba Capital',
    'Cosquín',
    'Cruz Alta',
    'Cruz del Eje',
    'Dean Funes',
    'Embalse',
    'Hernando',
    'Huerta Grande',
    'Jesús María',
    'Jovita',
    'Juárez Celman',
    'La Carlota',
    'La Falda',
    'La Para',
    'La Playosa',
    'Laboulaye',
    'Laguna Larga',
    'Las Perdices',
    'Las Varillas',
    'Leones',
    'Los Cocos',
    'Los Juríes',
    'Luque',
    'Malagueño',
    'Marcos Juárez',
    'Mina Clavero',
    'Monte Maíz',
    'Morrison',
    'Noetinger',
    'Oliva',
    'Oncativo',
    'Pilar',
    'Pueblo Italiano',
    'Río Ceballos',
    'Río Cuarto',
    'Río Segundo',
    'Río Tercero',
    'Sacanta',
    'San Francisco',
    'Santa María de Punilla',
    'Santa Rosa de Calamuchita',
    'Tancacha',
    'Ticino',
    'Tío Pujio',
    'Unquillo',
    'Valle Hermoso',
    'Villa Allende',
    'Villa Carlos Paz',
    'Villa Ciudad de América',
    'Villa Cura Brochero',
    'Villa Dolores',
    'Villa General Belgrano',
    'Villa Giardino',
    'Villa La Angostura',
    'Villa María',
    'Villa Nueva',
    'Villa Rumipal',
    'Villa del Lago',
    'Villa del Rosario',
    'Wenceslao Escalante',
  ],

  'Mendoza': [
    'Agrelo',
    'Barrancas',
    'Bardas Blancas',
    'Bowen',
    'Chacras de Coria',
    'Ciudad de Mendoza',
    'Eugenio Bustos',
    'General Alvear',
    'Godoy Cruz',
    'Guaymallén',
    'Junín',
    'La Paz',
    'Las Heras',
    'Lavalle',
    'Luján de Cuyo',
    'Maipú',
    'Malargüe',
    'Pedriel',
    'Perdriel',
    'Potrerillos',
    'Rivadavia',
    'San Carlos',
    'San Martín',
    'San Rafael',
    'Santa Rosa',
    'Tunuyán',
    'Tupungato',
    'Uspallata',
    'Vista Flores',
    'Vistalba',
  ],

  'Santa Fe': [
    'Alcorta',
    'Armstrong',
    'Avellaneda',
    'Bella Italia',
    'Bombal',
    'Cañada de Gómez',
    'Capitán Bermúdez',
    'Carlos Pellegrini',
    'Carcarañá',
    'Casilda',
    'Ceres',
    'Coronda',
    'El Trébol',
    'Esperanza',
    'Firmat',
    'Funes',
    'Gálvez',
    'Granadero Baigorria',
    'Hughes',
    'Laguna Paiva',
    'Las Parejas',
    'Las Rosas',
    'Malabrigo',
    'Pérez',
    'Rafaela',
    'Reconquista',
    'Rosario',
    'Rufino',
    'San Cristóbal',
    'San Genaro',
    'San Jorge',
    'San Justo',
    'San Lorenzo',
    'Santa Fe Capital',
    'Santo Tomé',
    'Sunchales',
    'Tostado',
    'Venado Tuerto',
    'Vera',
    'Villa Constitución',
    'Villa Gobernador Gálvez',
    'Wheelwright',
  ],

  'Salta': [
    'Cafayate',
    'Cachi',
    'Campo Quijano',
    'Chicoana',
    'El Bordo',
    'El Quebrachal',
    'Embarcación',
    'General Güemes',
    'Iruya',
    'Joaquín V. González',
    'La Caldera',
    'La Poma',
    'La Viña',
    'Metán',
    'Molinos',
    'Orán',
    'Payogasta',
    'Rivadavia',
    'Rosario de la Frontera',
    'Rosario de Lerma',
    'Salta Capital',
    'San Antonio de los Cobres',
    'San Ramón de la Nueva Orán',
    'Santa Rosa de Tastil',
    'Tartagal',
    'Tolar Grande',
    'Tolombón',
  ],

  'Jujuy': [
    'Abra Pampa',
    'El Aguilar',
    'El Carmen',
    'Fraile Pintado',
    'Humahuaca',
    'La Quiaca',
    'Libertador General San Martín',
    'Maimará',
    'Palpalá',
    'Purmamarca',
    'San Pedro de Jujuy',
    'San Salvador de Jujuy',
    'Santa Catalina',
    'Susques',
    'Tilcara',
    'Tumbaya',
    'Uquía',
    'Yavi',
  ],

  'Tucumán': [
    'Aguilares',
    'Alderetes',
    'Amaicha del Valle',
    'Banda del Río Salí',
    'Bella Vista',
    'Concepción',
    'El Cadillal',
    'Famaillá',
    'Graneros',
    'Juan Bautista Alberdi',
    'La Cocha',
    'Leales',
    'Lules',
    'Monteros',
    'San Miguel de Tucumán',
    'Simoca',
    'Tafí Viejo',
    'Tafí del Valle',
    'Trancas',
    'Yerba Buena',
  ],

  'Misiones': [
    'Apóstoles',
    'Aristóbulo del Valle',
    'Bernardo de Irigoyen',
    'Campo Grande',
    'Candelaria',
    'Capioví',
    'Colonia Aurora',
    'Colonia Delicia',
    'Colonia Victoria',
    'Dos de Mayo',
    'El Dorado',
    'Garupá',
    'Iguazú',
    'Jardín América',
    'Leandro N. Alem',
    'Loreto',
    'Montecarlo',
    'Oberá',
    'Posadas',
    'Puerto Esperanza',
    'Puerto Iguazú',
    'Puerto Libertad',
    'Puerto Piray',
    'Puerto Rico',
    'San Ignacio',
    'San Javier',
    'San Pedro',
    'Santa Ana',
    'Wanda',
  ],

  'Corrientes': [
    'Bella Vista',
    'Bonpland',
    'Chavarría',
    'Concepción',
    'Corrientes Capital',
    'Curuzú Cuatiá',
    'Empedrado',
    'Esquina',
    'Goya',
    'Itatí',
    'Ituzaingó',
    'Loreto',
    'Mburucuyá',
    'Mercedes',
    'Monte Caseros',
    'Paso de la Patria',
    'Saladas',
    'San Cosme',
    'San Luis del Palmar',
    'San Roque',
    'Santa Rosa',
    'Santo Tomé',
    'Yapeyú',
  ],

  'Entre Ríos': [
    'Basavilbaso',
    'Cerrito',
    'Chajarí',
    'Colón',
    'Concepción del Uruguay',
    'Concordia',
    'Crespo',
    'Diamante',
    'Federal',
    'Federación',
    'General Ramírez',
    'Gualeguay',
    'Gualeguaychú',
    'Hasenkamp',
    'Hernandarias',
    'La Paz',
    'Nogoyá',
    'Paraná',
    'San José',
    'Santa Elena',
    'Seguí',
    'Urdinarrain',
    'Victoria',
    'Villaguay',
  ],

  'Chubut': [
    'Alto Río Senguer',
    'Camarones',
    'Comodoro Rivadavia',
    'Dolavon',
    'El Maitén',
    'Esquel',
    'Gaiman',
    'Lago Puelo',
    'Las Plumas',
    'Puerto Madryn',
    'Puerto Pirámides',
    'Rada Tilly',
    'Rawson',
    'Río Mayo',
    'Río Senguer',
    'Sarmiento',
    'Tecka',
    'Trelew',
    'Trevelin',
  ],

  'Neuquén': [
    'Aluminé',
    'Andacollo',
    'Caviahue',
    'Centenario',
    'Copahue',
    'Cutral Có',
    'El Huecú',
    'Junín de los Andes',
    'Las Coloradas',
    'Las Lajas',
    'Loncopué',
    'Neuquén Capital',
    'Picún Leufú',
    'Plaza Huincul',
    'Plottier',
    'San Martín de los Andes',
    'San Patricio del Chañar',
    'Villa El Chocón',
    'Villa La Angostura',
    'Villa Pehuenia',
    'Zapala',
  ],

  'Río Negro': [
    'Allen',
    'Bariloche',
    'Cervantes',
    'Chichinales',
    'Choele Choel',
    'Cinco Saltos',
    'Cipolletti',
    'Comallo',
    'El Bolsón',
    'El Cuy',
    'Fray Luis Beltrán',
    'General Conesa',
    'General Fernández Oro',
    'General Roca',
    'Ingeniero Jacobacci',
    'Lamarque',
    'Las Grutas',
    'Los Menucos',
    'Mainqué',
    'Maquinchao',
    'Ministro Ramos Mexía',
    'Río Colorado',
    'San Antonio Oeste',
    'Sierra Colorada',
    'Sierra Grande',
    'Viedma',
    'Villa Regina',
  ],

  'San Luis': [
    'Arizona',
    'Buena Esperanza',
    'Carpintería',
    'Concarán',
    'Juan Martín de Pueyrredón',
    'Juana Koslay',
    'La Punta',
    'La Toma',
    'Merlo',
    'Naschel',
    'Potrero de los Funes',
    'Quines',
    'San Francisco del Monte de Oro',
    'San Luis Capital',
    'San Martín',
    'Tilisarao',
    'Villa Mercedes',
  ],

  'La Rioja': [
    'Aimogasta',
    'Chamical',
    'Chepes',
    'Chilecito',
    'Famatina',
    'General Ángel Vicente Peñaloza',
    'General Belgrano',
    'General Juan Facundo Quiroga',
    'Guandacol',
    'La Rioja Capital',
    'Patquía',
    'Ulapes',
    'Villa Sanagasta',
    'Villa Unión',
    'Vinchina',
  ],

  'Catamarca': [
    'Aconquija',
    'Andalgalá',
    'Antofagasta de la Sierra',
    'Belén',
    'Capayán',
    'El Rodeo',
    'Fiambalá',
    'Huillapima',
    'Icaño',
    'Londres',
    'Mutquín',
    'San Fernando del Valle de Catamarca',
    'Santa María',
    'Santa Rosa',
    'Tinogasta',
  ],

  'Formosa': [
    'Clorinda',
    'El Colorado',
    'Formosa Capital',
    'General Lucio Victorio Mansilla',
    'Ingeniero Juárez',
    'Las Lomitas',
    'Mayor Vicente Villafuerte',
    'Pirané',
    'Pozo del Tigre',
  ],

  'Chaco': [
    'Avia Terai',
    'Barranqueras',
    'Charata',
    'Chorotis',
    'Corzuela',
    'El Sauzal',
    'Fontana',
    'General San Martín',
    'Hermoso Campo',
    'Juan José Castelli',
    'La Escondida',
    'La Tigra',
    'Las Breñas',
    'Machagai',
    'Makallé',
    'Pampa del Indio',
    'Pampa del Infierno',
    'Presidencia de la Plaza',
    'Presidencia Roque Sáenz Peña',
    'Puerto Tirol',
    'Quitilipi',
    'Resistencia',
    'San Bernardo',
    'Santa Sylvina',
    'Taco Pozo',
    'Villa Ángela',
  ],

  'Santiago del Estero': [
    'Añatuya',
    'Bandera',
    'Campo Gallo',
    'Choya',
    'Fernández',
    'Frías',
    'Garza',
    'La Banda',
    'Loreto',
    'Los Juríes',
    'Miraflores',
    'Monte Quemado',
    'Nueva Esperanza',
    'Quimilí',
    'Robles',
    'Santiago del Estero Capital',
    'Selva',
    'Suncho Corral',
    'Termas de Río Hondo',
    'Tintina',
    'Villa Atamisqui',
  ],

  'San Juan': [
    'Albardón',
    'Angaco',
    'Barreal',
    'Calingasta',
    'Caucete',
    'Chimbas',
    'Iglesia',
    'Jachal',
    'Media Agua',
    'Pocito',
    'Rawson',
    'Rivadavia',
    'San Juan Capital',
    'Santa Lucía',
    'Sarmiento',
    'Ullum',
    'Valle Fértil',
    'Zonda',
  ],

  'La Pampa': [
    'Anguil',
    'Catriló',
    'Eduardo Castex',
    'General Acha',
    'General Pico',
    'Guatraché',
    'Ingeniero Luiggi',
    'Intendente Alvear',
    'Macachín',
    'Maisonnave',
    'Metileo',
    'Quemú Quemú',
    'Realicó',
    'Santa Isabel',
    'Santa Rosa',
    'Speluzzi',
    'Telén',
    'Toay',
    'Trenel',
    'Uriburu',
    'Victorica',
    'Winifreda',
  ],

  'Santa Cruz': [
    'Caleta Olivia',
    'Cañadón Seco',
    'El Calafate',
    'El Chaltén',
    'El Turbio',
    'Gobernador Gregores',
    'Las Heras',
    'Los Antiguos',
    'Perito Moreno',
    'Piedra Buena',
    'Puerto Deseado',
    'Puerto San Julián',
    'Río Gallegos',
    'Río Turbio',
  ],

  'Tierra del Fuego': [
    'Río Grande',
    'Tolhuin',
    'Ushuaia',
  ],
}
