export const ARGENTINA_LOCATIONS: Record<string, Record<string, string[]>> = {
  'Buenos Aires': {
    'Adolfo Alsina': ['Adolfo Alsina', 'Carhué'].sort(),
    'Adolfo Gonzales Chaves': ['Adolfo Gonzales Chaves', 'Colonia San Martín'].sort(),
    'Alberti': ['Alberti', 'Mechita'].sort(),
    'Almirante Brown': [
      'Adrogué', 'Burzaco', 'Claypole', 'Don Orione', 'Glew', 'Longchamps',
      'Malvinas Argentinas', 'Ministro Rivadavia', 'Rafael Calzada', 'San Francisco de Asís',
    ].sort(),
    'Arrecifes': ['Arrecifes', 'Todd'].sort(),
    'Avellaneda': ['Avellaneda', 'Dock Sud', 'Gerli', 'Lanús'].sort(),
    'Ayacucho': ['Ayacucho', 'Solanet'].sort(),
    'Azul': ['Azul', 'Cacharí', 'Chillar'].sort(),
    'Bahía Blanca': ['Aldea Romana', 'Bahía Blanca', 'General Daniel Cerri', 'Grünbein'].sort(),
    'Balcarce': ['Balcarce', 'Los Pinos', 'Napaleofú'].sort(),
    'Baradero': ['Baradero', 'Irineo Portela'].sort(),
    'Benito Juárez': ['Barker', 'Benito Juárez', 'López'].sort(),
    'Berazategui': ['Berazategui', 'Florencio Varela', 'Hudson', 'Ranelagh'].sort(),
    'Berisso': ['Berisso', 'Villa Argüello'].sort(),
    'Bolívar': ['Bolívar', 'Hale', 'Pirovano', 'Urdampilleta'].sort(),
    'Bragado': ['Bragado', 'Mechita', "O'Brien", 'Vedia'].sort(),
    'Brandsen': ['Brandsen', 'Gómez', 'La Paz'].sort(),
    'Campana': ['Campana', 'Otamendi', 'Zárate'].sort(),
    'Cañuelas': ['Cañuelas', 'Uribelarrea'].sort(),
    'Capitán Sarmiento': ['Capitán Sarmiento', 'El Triunfo'].sort(),
    'Carlos Casares': ['Carlos Casares', 'Moctezuma', 'Urquiza'].sort(),
    'Carlos Tejedor': ['Carlos Tejedor', 'Colonia Sere', 'Timote'].sort(),
    'Carmen de Areco': ['Carmen de Areco'].sort(),
    'Chacabuco': ['Chacabuco', 'Rawson'].sort(),
    'Chascomús': ['Chascomús', 'Lezama'].sort(),
    'Chivilcoy': ['Chivilcoy', 'Moquehuá'].sort(),
    'Colón': ['Colón', 'Pearson', 'Villa María'].sort(),
    'Coronel Dorrego': ['Coronel Dorrego', 'Oriente'].sort(),
    'Coronel Pringles': ['Coronel Pringles', 'Indio Rico'].sort(),
    'Coronel Rosales': ['Baterías', 'Punta Alta'].sort(),
    'Coronel Suárez': ['Coronel Suárez', 'Darregueira', 'Huanguelen', 'Pasman', 'San José'].sort(),
    'Dolores': ['Dolores', 'Sevigne'].sort(),
    'Ensenada': ['Ensenada', 'Punta Lara'].sort(),
    'Escobar': ['Belén de Escobar', 'Escobar', 'Garín', 'Ingeniero Maschwitz', 'Maquinista Savio'].sort(),
    'Esteban Echeverría': ['Canning', 'El Jagüel', 'Monte Grande'].sort(),
    'Exaltación de la Cruz': ['Capilla del Señor', 'Cardales', 'Parada Robles'].sort(),
    'Ezeiza': ['Ezeiza', 'La Unión', 'Luis Guillón', 'Tristán Suárez'].sort(),
    'Florencio Varela': ['Florencio Varela', 'Gobernador Julio Costa', 'Villa Brown'].sort(),
    'General Alvarado': ['Mar del Sur', 'Miramar'].sort(),
    'General Alvear': ['Dos Naciones', 'General Alvear', 'Urdampilleta'].sort(),
    'General Arenales': ['Ferré', 'General Arenales'].sort(),
    'General Belgrano': ['General Belgrano'].sort(),
    'General Guido': ['General Guido'].sort(),
    'General Juan Madariaga': ['General Juan Madariaga', 'Pinamar adjacent'].sort(),
    'General La Madrid': ['General La Madrid'].sort(),
    'General Las Heras': ['General Las Heras'].sort(),
    'General Lavalle': ['General Lavalle', 'Pavón'].sort(),
    'General Paz': ['General Paz', 'Ranchos'].sort(),
    'General Pinto': ['General Pinto', 'Iriarte'].sort(),
    'General Pueyrredón': ['Batán', 'Mar del Plata'].sort(),
    'General Rodríguez': ['General Rodríguez'].sort(),
    'General Viamonte': ['América', 'Los Toldos'].sort(),
    'General Villegas': ['General Villegas', 'Piedritas'].sort(),
    'Gonzales Chaves': ['Gonzales Chaves'].sort(),
    'Guaminí': ['Casbas', 'Guaminí', 'Laguna Alsina'].sort(),
    'Hipólito Yrigoyen': ['Henderson', 'Mones Cazón'].sort(),
    'Hurlingham': ['Hurlingham', 'William Morris'].sort(),
    'Ituzaingó': ['Ituzaingó', 'Padua'].sort(),
    'José C. Paz': ['José C. Paz'].sort(),
    'Junín': ['Junín', 'Saforcada'].sort(),
    'La Matanza': [
      'González Catán', 'Gregorio de Laferrere', 'Isidro Casanova', 'Laferrere',
      'Ramos Mejía', 'San Justo', 'Tapiales', 'Villa Luzuriaga',
    ].sort(),
    'La Plata': ['City Bell', 'Gonnet', 'La Plata', 'Los Hornos'].sort(),
    'Lanús': ['Gerli', 'Lanús', 'Monte Chingolo', 'Remedios de Escalada'].sort(),
    'Laprida': ['Laprida'].sort(),
    'Las Flores': ['Las Flores', 'Verónica'].sort(),
    'Leandro N. Alem': ['Ayacucho', 'Leandro N. Alem'].sort(),
    'Lincoln': ['Arenaza', 'Lincoln'].sort(),
    'Lobería': ['Lobería', 'Nicanor Olivera'].sort(),
    'Lobos': ['Lobos'].sort(),
    'Lomas de Zamora': ['Banfield', 'Lomas de Zamora', 'Temperley', 'Turdera'].sort(),
    'Luján': ['Luján', 'Open Door', 'Torres'].sort(),
    'Maipú': ['Coronel Boerr', 'Maipú'].sort(),
    'Malvinas Argentinas': ['Grand Bourg', 'Ing. Pablo Nogués', 'Los Polvorines'].sort(),
    'Mar Chiquita': ['Camet Norte', 'Mar Chiquita', 'Santa Clara del Mar'].sort(),
    'Marcos Paz': ['Marcos Paz'].sort(),
    'Mercedes': ['Mercedes'].sort(),
    'Merlo': ['Libertad', 'Merlo', 'Pontevedra'].sort(),
    'Moreno': ['Cuartel V', 'Moreno', 'Trujui'].sort(),
    'Morón': ['El Palomar', 'Haedo', 'Morón'].sort(),
    'Navarro': ['Navarro'].sort(),
    'Necochea': ['Necochea', 'Quequén', 'Ramón Santamarina'].sort(),
    'Nueve de Julio': ['Carlos Salas', 'Nueve de Julio'].sort(),
    'Olavarría': ['Hinojo', 'Olavarría', 'Sierras Bayas'].sort(),
    'Patagones': ['Carmen de Patagones', 'Villalonga'].sort(),
    'Pehuajó': ['Chiclana', 'Mones Cazón', 'Pehuajó'].sort(),
    'Pellegrini': ['Pellegrini', 'Saavedra'].sort(),
    'Pergamino': ['Juan Anchorena', 'Pergamino'].sort(),
    'Pilar': ['Del Viso', 'Manzanares', 'Pilar'].sort(),
    'Pinamar': ['Cariló', 'Ostende', 'Pinamar', 'Valeria del Mar'].sort(),
    'Presidente Perón': ['Guernica'].sort(),
    'Puán': ['Bordenave', 'Darregueira', 'Felipe Solá', 'Puán'].sort(),
    'Punta Indio': ['Pipinas'].sort(),
    'Quilmes': ['Bernal', 'Berazategui', 'Quilmes'].sort(),
    'Ramallo': ['Ramallo', 'Villa Ramallo'].sort(),
    'Rauch': ['Rauch'].sort(),
    'Rivadavia': ['América', 'Sansinena'].sort(),
    'Rojas': ['Carabelas', 'Rojas'].sort(),
    'Roque Pérez': ['Roque Pérez'].sort(),
    'Saavedra': ['Espartillar', 'Pigüé'].sort(),
    'Saladillo': ['Del Carril', 'Saladillo'].sort(),
    'Salliqueló': ['Espartillar', 'Salliqueló'].sort(),
    'Salto': ['Inés Indart', 'Salto'].sort(),
    'San Andrés de Giles': ['Azcuénaga', 'San Andrés de Giles'].sort(),
    'San Antonio de Areco': ['Duggan', 'San Antonio de Areco'].sort(),
    'San Bernardo': [
      'Costa del Este', 'Las Toninas', 'Mar de Ajó', 'Mar del Tuyú', 'San Bernardo', 'Santa Teresita',
    ].sort(),
    'San Cayetano': ['San Cayetano'].sort(),
    'San Fernando': ['San Fernando', 'Victoria'].sort(),
    'San Isidro': ['Beccar', 'Boulogne', 'Martínez', 'San Isidro'].sort(),
    'San Miguel': ['Bella Vista', 'Muñiz', 'San Miguel'].sort(),
    'San Nicolás': ['San Nicolás', 'Villa Constitución'].sort(),
    'San Pedro': ['Gobernador Castro', 'San Pedro'].sort(),
    'San Vicente': ['Alejandro Korn', 'San Vicente'].sort(),
    'Suipacha': ['Suipacha'].sort(),
    'Tandil': ['Gardey', 'Tandil'].sort(),
    'Tapalqué': ['Crotto', 'Tapalqué'].sort(),
    'Tigre': ['Don Torcuato', 'General Pacheco', 'Ricardo Rojas', 'Tigre'].sort(),
    'Tordillo': ['General Conesa'].sort(),
    'Tornquist': ['Chasicó', 'Pehuen-Co', 'Saldungaray', 'Sierra de la Ventana', 'Tornquist', 'Villa Ventana'].sort(),
    'Trenque Lauquen': ['Girodías', 'La Zanja', 'Trenque Lauquen'].sort(),
    'Tres Arroyos': ['Claromecó', 'Orense', 'Tres Arroyos'].sort(),
    'Tres de Febrero': ['Caseros', 'Ciudadela', 'Pablo Podestá', 'Saenz Peña'].sort(),
    'Tres Lomas': ['Tres Lomas'].sort(),
    'Veinticinco de Mayo': ['Norberto de la Riestra', 'Veinticinco de Mayo'].sort(),
    'Vicente López': ['Florida', 'La Lucila', 'Martínez', 'Munro', 'Olivos', 'Vicente López'].sort(),
    'Villa Gesell': ['Las Gaviotas', 'Mar de las Pampas', 'Villa Gesell'].sort(),
    'Villarino': ['Mayor Buratovich', 'Médanos', 'Teniente Origone'].sort(),
    'Zárate': ['Lima', 'Zárate'].sort(),
  },

  'CABA': {
    'Comuna 1': ['Constitución', 'Microcentro', 'Monserrat', 'Puerto Madero', 'Retiro', 'San Nicolás', 'San Telmo'].sort(),
    'Comuna 2': ['Recoleta'].sort(),
    'Comuna 3': ['Balvanera', 'San Cristóbal'].sort(),
    'Comuna 4': ['Barracas', 'La Boca', 'Nueva Pompeya', 'Parque Patricios'].sort(),
    'Comuna 5': ['Almagro', 'Boedo'].sort(),
    'Comuna 6': ['Caballito'].sort(),
    'Comuna 7': ['Flores', 'Parque Chacabuco'].sort(),
    'Comuna 8': ['Nueva Chicago', 'Villa Lugano', 'Villa Riachuelo', 'Villa Soldati'].sort(),
    'Comuna 9': ['Liniers', 'Mataderos', 'Parque Avellaneda'].sort(),
    'Comuna 10': ['Floresta', 'Monte Castro', 'Vélez Sársfield', 'Versalles', 'Villa Luro', 'Villa Real'].sort(),
    'Comuna 11': ['Agronomía', 'La Paternal', 'Villa del Parque', 'Villa Devoto', 'Villa General Mitre', 'Villa Santa Rita'].sort(),
    'Comuna 12': ['Coghlan', 'Saavedra', 'Villa Pueyrredón', 'Villa Urquiza'].sort(),
    'Comuna 13': ['Belgrano', 'Colegiales', 'Núñez'].sort(),
    'Comuna 14': ['Las Cañitas', 'Palermo', 'Palermo Chico', 'Palermo Hollywood', 'Palermo Soho'].sort(),
    'Comuna 15': ['Chacarita', 'Parque Chas', 'Villa Crespo', 'Villa Ortúzar'].sort(),
  },

  'Catamarca': {
    'Ambato': ['El Rodeo', 'La Puerta', 'Los Varela'].sort(),
    'Ancasti': ['Ancasti'].sort(),
    'Andalgalá': ['Andalgalá', 'Aconquija', 'Choya'].sort(),
    'Antofagasta de la Sierra': ['Antofagasta de la Sierra'].sort(),
    'Belén': ['Belén', 'Fiambalá', 'Hualfín', 'Londres', 'Mutquín', 'Tinogasta'].sort(),
    'Capital': ['San Fernando del Valle de Catamarca'].sort(),
    'Capayán': ['Capayán', 'Huillapima', 'Icaño'].sort(),
    'El Alto': ['El Alto'].sort(),
    'Fray Mamerto Esquiú': ['Piedra Blanca'].sort(),
    'La Paz': ['Recreo', 'Santa Rosa'].sort(),
    'Paclín': ['La Merced'].sort(),
    'Pomán': ['Pomán', 'Saujil'].sort(),
    'Santa María': ['Santa María'].sort(),
    'Santa Rosa': ['Santa Rosa'].sort(),
    'Tinogasta': ['Fiambalá', 'Tinogasta'].sort(),
    'Valle Viejo': ['Valle Viejo'].sort(),
  },

  'Chaco': {
    '1º de Mayo': ['Colonia Benítez', 'Margarita Belén'].sort(),
    '12 de Octubre': ['Gancedo', 'Hermoso Campo'].sort(),
    '2 de Abril': ['Chorotis', 'Santa Sylvina'].sort(),
    '25 de Mayo': ['Machagai', 'Pampa del Indio'].sort(),
    '9 de Julio': ['Las Breñas'].sort(),
    'Almirante Brown': ['Pampa del Infierno', 'Taco Pozo'].sort(),
    'Comandante Fernández': ['Presidencia Roque Sáenz Peña'].sort(),
    'Chacabuco': ['Charata'].sort(),
    'Fray Justo Santa María de Oro': ['La Tigra'].sort(),
    'General Belgrano': ['Corzuela'].sort(),
    'General Donovan': ['Makallé'].sort(),
    'General Güemes': ['Juan José Castelli', 'Miraflores'].sort(),
    'Independencia': ['Avia Terai', 'Quitilipi'].sort(),
    'Libertad': ['San Bernardo'].sort(),
    'Libertador General San Martín': ['General San Martín'].sort(),
    'Maipú': ['Ciervo Petiso', 'El Sauzal'].sort(),
    'Mayor Luis Jorge Fontana': ['La Escondida', 'Villa Ángela'].sort(),
    'O\'Higgins': ['Charata'].sort(),
    'Presidencia de la Plaza': ['Presidencia de la Plaza'].sort(),
    'Quitilipi': ['Quitilipi'].sort(),
    'San Fernando': ['Barranqueras', 'Fontana', 'Puerto Tirol', 'Resistencia'].sort(),
    'San Lorenzo': ['El Zapallar', 'Villa Berthet'].sort(),
    'Tapenagá': ['Charadai'].sort(),
    'Veinticinco de Mayo': ['Los Frentones'].sort(),
  },

  'Chubut': {
    'Biedma': ['Madryn', 'Puerto Madryn', 'Puerto Pirámides'].sort(),
    'Cushamen': ['El Maitén', 'Epuyén', 'Lago Puelo'].sort(),
    'Escalante': ['Caleta Olivia', 'Comodoro Rivadavia', 'Rada Tilly'].sort(),
    'Florentino Ameghino': ['Las Plumas'].sort(),
    'Futaleufú': ['Esquel', 'Trevelin'].sort(),
    'Gaiman': ['Dolavon', 'Gaiman'].sort(),
    'Gastre': ['Gastre'].sort(),
    'Languiñeo': ['Tecka'].sort(),
    'Mártires': ['Las Plumas'].sort(),
    'Paso de Indios': ['Paso de Indios'].sort(),
    'Rawson': ['Playa Unión', 'Rawson', 'Trelew'].sort(),
    'Río Senguer': ['Alto Río Senguer', 'Río Mayo', 'Sarmiento'].sort(),
    'Sarmiento': ['Sarmiento'].sort(),
    'Tehuelches': ['José de San Martín'].sort(),
    'Tierra del Fuego': ['Camarones'].sort(),
  },

  'Córdoba': {
    'Calamuchita': ['Alta Gracia', 'Embalse', 'Santa Rosa de Calamuchita', 'Villa del Dique', 'Villa General Belgrano'].sort(),
    'Capital': ['Córdoba'].sort(),
    'Colón': ['Jesús María', 'La Calera', 'Mendiolaza', 'Río Ceballos', 'Unquillo', 'Villa Allende'].sort(),
    'Cruz del Eje': ['Cruz del Eje', 'Serrezuela'].sort(),
    'General Roca': ['Berrotarán', 'General Roca'].sort(),
    'Ischilín': ['Deán Funes', 'Quilino'].sort(),
    'Juárez Celman': ['La Carlota'].sort(),
    'Marcos Juárez': ['Bell Ville', 'Marcos Juárez'].sort(),
    'Minas': ['Mina Clavero', 'Nono'].sort(),
    'Pocho': ['Salsacate'].sort(),
    'Punilla': [
      'Capilla del Monte', 'Cosquín', 'Huerta Grande', 'La Cumbre', 'La Falda',
      'Los Cocos', 'Valle Hermoso', 'Villa Carlos Paz', 'Villa Giardino',
    ].sort(),
    'Río Cuarto': ['Adelia María', 'Río Cuarto'].sort(),
    'Río Primero': ['Santa Rosa de Río Primero'].sort(),
    'Río Seco': ['Sebastián Elcano'].sort(),
    'San Alberto': ['Mina Clavero', 'Nono', 'Villa Cura Brochero'].sort(),
    'San Javier': ['Luyaba', 'Villa Dolores'].sort(),
    'San Justo': ['Brinkmann', 'San Francisco'].sort(),
    'Santa María': ['Alta Gracia', 'Anisacate'].sort(),
    'Sobremonte': ['San Francisco del Chañar'].sort(),
    'Tercero Arriba': ['Almafuerte', 'Río Tercero'].sort(),
    'Totoral': ['Totoral'].sort(),
    'Tulumba': ['Villa de María'].sort(),
    'Unión': ['Bell Ville', 'Canals', 'Las Varillas'].sort(),
  },

  'Corrientes': {
    'Bella Vista': ['Bella Vista'].sort(),
    'Berón de Astrada': ['Berón de Astrada'].sort(),
    'Capital': ['Corrientes'].sort(),
    'Concepción': ['Concepción', 'Loreto', 'Mburucuyá', 'San Miguel'].sort(),
    'Curuzú Cuatiá': ['Curuzú Cuatiá'].sort(),
    'Empedrado': ['Empedrado'].sort(),
    'Esquina': ['Esquina'].sort(),
    'General Alvear': ['Alvear'].sort(),
    'General Paz': ['Chavarría', 'Mercedes'].sort(),
    'Goya': ['Goya'].sort(),
    'Itatí': ['Itatí'].sort(),
    'Ituzaingó': ['Ituzaingó'].sort(),
    'Lavalle': ['Santa Rosa', 'Yapeyu'].sort(),
    'Mburucuyá': ['Mburucuyá'].sort(),
    'Mercedes': ['Mercedes'].sort(),
    'Monte Caseros': ['Monte Caseros', 'Mocoretá'].sort(),
    'Paso de la Patria': ['Paso de la Patria'].sort(),
    'Saladas': ['Saladas'].sort(),
    'San Cosme': ['Bonpland', 'San Cosme'].sort(),
    'San Luis del Palmar': ['San Luis del Palmar'].sort(),
    'San Martín': ['Yapeyú'].sort(),
    'San Miguel': ['San Miguel'].sort(),
    'San Roque': ['San Roque'].sort(),
    'Santo Tomé': ['Santo Tomé'].sort(),
  },

  'Entre Ríos': {
    'Colón': ['Colón', 'San José', 'Villa Elisa'].sort(),
    'Concordia': ['Concordia', 'Los Charrúas'].sort(),
    'Diamante': ['Diamante', 'General Ramírez'].sort(),
    'Federación': ['Chajarí', 'Federación', 'San Jaime de la Frontera'].sort(),
    'Federal': ['Federal'].sort(),
    'Feliciano': ['San José de Feliciano'].sort(),
    'Gualeguay': ['Gualeguay', 'Urdinarrain'].sort(),
    'Gualeguaychú': ['Gualeguaychú', 'Larroque'].sort(),
    'Islas del Ibicuy': ['Gualeguaychú'].sort(),
    'La Paz': ['La Paz', 'Santa Elena'].sort(),
    'Nogoyá': ['Nogoyá'].sort(),
    'Paraná': ['Crespo', 'Hasenkamp', 'Hernandarias', 'Paraná', 'Seguí'].sort(),
    'Tala': ['Cerrito', 'General Ramírez', 'Rosario del Tala'].sort(),
    'Uruguay': ['Basavilbaso', 'Concepción del Uruguay', 'Villa Elisa'].sort(),
    'Victoria': ['Victoria'].sort(),
    'Villaguay': ['Villaguay'].sort(),
  },

  'Formosa': {
    'Bermejo': ['Ingeniero Juárez', 'Las Lomitas'].sort(),
    'Formosa': ['Clorinda', 'El Colorado', 'Formosa', 'Pirané'].sort(),
    'Laishí': ['General Lucio Victorio Mansilla'].sort(),
    'Matacos': ['Ingeniero Juárez'].sort(),
    'Patiño': ['Las Lomitas', 'Pozo del Tigre'].sort(),
    'Pilcomayo': ['Clorinda'].sort(),
    'Pilagás': ['Mayor Vicente Villafuerte'].sort(),
    'Ramón Lista': ['Ingeniero Juárez'].sort(),
  },

  'Jujuy': {
    'Cochinoca': ['Abra Pampa', 'Casabindo', 'Cochinoca'].sort(),
    'Dr. Manuel Belgrano': ['San Salvador de Jujuy'].sort(),
    'El Carmen': ['El Carmen', 'Perico'].sort(),
    'Humahuaca': ['Humahuaca', 'Iruya', 'Uquía'].sort(),
    'Ledesma': ['Fraile Pintado', 'Libertador General San Martín'].sort(),
    'Palpalá': ['Palpalá'].sort(),
    'Quebrada de Humahuaca': ['Maimará', 'Purmamarca', 'Tilcara', 'Tumbaya'].sort(),
    'Rinconada': ['La Rinconada'].sort(),
    'San Antonio': ['El Aguilar'].sort(),
    'San Pedro': ['San Pedro de Jujuy'].sort(),
    'Santa Bárbara': ['El Fuerte', 'Santa Clara'].sort(),
    'Santa Catalina': ['La Quiaca', 'Santa Catalina', 'Yavi'].sort(),
    'Susques': ['Susques'].sort(),
    'Tilcara': ['Maimará', 'Tilcara'].sort(),
    'Tumbaya': ['Purmamarca', 'Tumbaya'].sort(),
    'Valle Grande': ['Valle Grande'].sort(),
    'Yavi': ['La Quiaca', 'Yavi'].sort(),
  },

  'La Pampa': {
    'Atreucó': ['Macachín'].sort(),
    'Caleu Caleu': ['La Humada'].sort(),
    'Capital': ['Santa Rosa', 'Toay'].sort(),
    'Catriló': ['Catriló', 'Quemú Quemú'].sort(),
    'Chalileo': ['Santa Isabel'].sort(),
    'Chapaleufú': ['Intendente Alvear', 'Realicó'].sort(),
    'Chicalcó': ['Chos Malal'].sort(),
    'Conhelo': ['Eduardo Castex'].sort(),
    'Curacó': ['Puelches'].sort(),
    'General Acha': ['General Acha'].sort(),
    'Guatraché': ['Guatraché'].sort(),
    'Hucal': ['Bernasconi'].sort(),
    'Lihuel Calel': ['La Reforma'].sort(),
    'Limay Mahuida': ['Limay Mahuida'].sort(),
    'Loventué': ['Victorica'].sort(),
    'Maracó': ['General Pico'].sort(),
    'Puelén': ['25 de Mayo'].sort(),
    'Quemú Quemú': ['Quemú Quemú'].sort(),
    'Rancul': ['Parera'].sort(),
    'Realicó': ['Maisonnave', 'Realicó', 'Speluzzi', 'Trenel', 'Winifreda'].sort(),
    'Toay': ['Anguil', 'Toay'].sort(),
    'Trenel': ['Trenel'].sort(),
    'Utracan': ['General Acha'].sort(),
  },

  'La Rioja': {
    'Arauco': ['Aimogasta'].sort(),
    'Capital': ['La Rioja'].sort(),
    'Castro Barros': ['Aminga', 'Chuquis', 'Los Molinos'].sort(),
    'Chamical': ['Chamical'].sort(),
    'Chilecito': ['Chilecito', 'Famatina', 'Villa Unión'].sort(),
    'Coronel Felipe Varela': ['Guandacol', 'Vinchina'].sort(),
    'Dávila': ['Olta'].sort(),
    'Famatina': ['Famatina'].sort(),
    'General Ángel Vicente Peñaloza': ['Chepes', 'Ulapes'].sort(),
    'General Belgrano': ['Patquía'].sort(),
    'General Juan Facundo Quiroga': ['Pagancillo', 'Villa Unión'].sort(),
    'General San Martín': ['Los Sarmientos'].sort(),
    'Independencia': ['Patquía'].sort(),
    'Rosario Vera Peñaloza': ['Chepes'].sort(),
    'San Blas de los Sauces': ['San Blas'].sort(),
    'Sanagasta': ['Villa Sanagasta'].sort(),
    'Vinchina': ['Guandacol', 'Villa Unión', 'Vinchina'].sort(),
  },

  'Mendoza': {
    'Capital': ['Mendoza'].sort(),
    'General Alvear': ['General Alvear'].sort(),
    'Godoy Cruz': ['Godoy Cruz'].sort(),
    'Guaymallén': ['Guaymallén', 'Rodeo del Medio'].sort(),
    'Junín': ['Junín'].sort(),
    'La Paz': ['La Paz'].sort(),
    'Las Heras': ['Las Heras', 'Uspallata'].sort(),
    'Lavalle': ['Lavalle', 'Villa Tulumaya'].sort(),
    'Luján de Cuyo': ['Agrelo', 'Chacras de Coria', 'Luján de Cuyo', 'Perdriel', 'Potrerillos'].sort(),
    'Maipú': ['Coquimbito', 'Maipú'].sort(),
    'Malargüe': ['Malargüe'].sort(),
    'Rivadavia': ['Rivadavia'].sort(),
    'San Carlos': ['Eugenio Bustos', 'San Carlos', 'Tupungato'].sort(),
    'San Martín': ['Palmira', 'San Martín'].sort(),
    'San Rafael': ['Las Paredes', 'Monte Coman', 'San Rafael'].sort(),
    'Santa Rosa': ['Santa Rosa'].sort(),
    'Tunuyán': ['Tunuyán', 'Vista Flores'].sort(),
    'Tupungato': ['Tupungato'].sort(),
  },

  'Misiones': {
    'Apóstoles': ['Apóstoles', 'San José'].sort(),
    'Cainguás': ['Aristóbulo del Valle', 'Campo Grande'].sort(),
    'Candelaria': ['Candelaria', 'Santa Ana'].sort(),
    'Capital': ['Garupá', 'Posadas'].sort(),
    'Concepción': ['Concepción de la Sierra', 'Santa María'].sort(),
    'El Dorado': ['El Dorado', 'Puerto Libertad'].sort(),
    'General Manuel Belgrano': ['Bernardo de Irigoyen', 'San Pedro'].sort(),
    'Guaraní': ['Colonia Aurora', 'El Soberbio'].sort(),
    'Iguazú': ['Iguazú', 'Puerto Esperanza', 'Puerto Iguazú'].sort(),
    'Leandro N. Alem': ['Dos Arroyos', 'Leandro N. Alem'].sort(),
    'Libertador General San Martín': ['Capioví', 'Jardín América', 'Puerto Rico'].sort(),
    'Montecarlo': ['Montecarlo', 'Puerto Piray'].sort(),
    'Oberá': ['Campo Ramón', 'Oberá'].sort(),
    'San Ignacio': ['Loreto', 'San Ignacio', 'Wanda'].sort(),
    'San Javier': ['San Javier'].sort(),
    'San Pedro': ['San Pedro'].sort(),
    'Veinticinco de Mayo': ['Colonia Delicia', 'Colonia Victoria', 'Dos de Mayo', 'San Vicente'].sort(),
  },

  'Neuquén': {
    'Aluminé': ['Aluminé', 'Villa Pehuenia'].sort(),
    'Añelo': ['Añelo', 'San Patricio del Chañar'].sort(),
    'Catán Lil': ['Las Coloradas'].sort(),
    'Collón Cura': ['Junín de los Andes'].sort(),
    'Confluencia': ['Centenario', 'Neuquén', 'Plottier'].sort(),
    'Chos Malal': ['Andacollo', 'Chos Malal'].sort(),
    'Huiliches': ['Junín de los Andes'].sort(),
    'Lacar': ['San Martín de los Andes'].sort(),
    'Loncopué': ['Loncopué'].sort(),
    'Los Lagos': ['Villa La Angostura', 'Villa Traful'].sort(),
    'Minas': ['Andacollo'].sort(),
    'Ñorquín': ['Caviahue', 'Copahue', 'El Huecú'].sort(),
    'Pehuenches': ['Las Lajas', 'Loncopué'].sort(),
    'Picún Leufú': ['Picún Leufú'].sort(),
    'Picunches': ['Las Lajas'].sort(),
    'Plaza Huincul': ['Cutral Có', 'Plaza Huincul'].sort(),
    'Zapala': ['Las Lajas', 'Villa El Chocón', 'Zapala'].sort(),
  },

  'Río Negro': {
    'Adolfo Alsina': ['Choele Choel', 'Lamarque', 'Luis Beltrán'].sort(),
    'Avellaneda': ['Guardia Mitre', 'Pomona'].sort(),
    'Bariloche': ['Bariloche', 'El Bolsón'].sort(),
    'Conesa': ['General Conesa'].sort(),
    'El Cuy': ['El Cuy'].sort(),
    'General Roca': ['Allen', 'Cervantes', 'Chichinales', 'Cinco Saltos', 'Cipolletti', 'Fray Luis Beltrán', 'General Fernández Oro', 'General Roca', 'Mainqué', 'Villa Regina'].sort(),
    'Ñorquinco': ['Ñorquinco'].sort(),
    'Nueve de Julio': ['Ingeniero Jacobacci', 'Maquinchao'].sort(),
    'Pilcaniyeu': ['Comallo', 'Río Negro'].sort(),
    'San Antonio': ['Las Grutas', 'San Antonio Oeste', 'Sierra Grande'].sort(),
    'Valcheta': ['Valcheta'].sort(),
    'Viedma': ['Viedma'].sort(),
    '25 de Mayo': ['Los Menucos'].sort(),
    'Pichi Mahuida': ['Río Colorado'].sort(),
    'Paso de Los Indios': ['Los Menucos', 'Sierra Colorada'].sort(),
    'Ministro Ramos Mexía': ['Ministro Ramos Mexía'].sort(),
  },

  'Salta': {
    'Anta': ['Joaquín V. González', 'Las Lajitas'].sort(),
    'Cachi': ['Cachi', 'Payogasta'].sort(),
    'Cafayate': ['Cafayate'].sort(),
    'Campo Santo': ['Campo Santo'].sort(),
    'Candelaria': ['Candelaria'].sort(),
    'Capital': ['Salta'].sort(),
    'Cerrillos': ['Cerrillos', 'Rosario de Lerma'].sort(),
    'Chicoana': ['Chicoana'].sort(),
    'General Güemes': ['El Bordo', 'General Güemes'].sort(),
    'General José de San Martín': ['Embarcación', 'Tartagal'].sort(),
    'Guachipas': ['Alemania', 'Guachipas'].sort(),
    'Iruya': ['Iruya'].sort(),
    'La Caldera': ['Campo Quijano', 'La Caldera'].sort(),
    'La Candelaria': ['La Candelaria'].sort(),
    'La Poma': ['La Poma'].sort(),
    'La Viña': ['La Viña'].sort(),
    'Los Andes': ['San Antonio de los Cobres', 'Tolar Grande'].sort(),
    'Metán': ['El Quebrachal', 'Metán', 'Rosario de la Frontera'].sort(),
    'Molinos': ['Molinos'].sort(),
    'Orán': ['Orán', 'San Ramón de la Nueva Orán'].sort(),
    'Rivadavia': ['Rivadavia'].sort(),
    'Rosario de la Frontera': ['Rosario de la Frontera'].sort(),
    'Rosario de Lerma': ['Rosario de Lerma'].sort(),
    'Santa Rosa de Tastil': ['Santa Rosa de Tastil'].sort(),
    'Tolombón': ['Tolombón'].sort(),
  },

  'San Juan': {
    'Albardón': ['Albardón'].sort(),
    'Angaco': ['Angaco'].sort(),
    'Calingasta': ['Barreal', 'Calingasta'].sort(),
    'Capital': ['San Juan'].sort(),
    'Caucete': ['Caucete'].sort(),
    'Chimbas': ['Chimbas'].sort(),
    'Iglesia': ['Iglesia', 'Rodeo'].sort(),
    'Jáchal': ['Jachal'].sort(),
    'Nueve de Julio': ['Arroyito'].sort(),
    'Pocito': ['Media Agua', 'Pocito'].sort(),
    'Rawson': ['Rawson'].sort(),
    'Rivadavia': ['Rivadavia'].sort(),
    'San Martín': ['Carpintería'].sort(),
    'Santa Lucía': ['Santa Lucía'].sort(),
    'Sarmiento': ['Sarmiento'].sort(),
    'Ullum': ['Ullum'].sort(),
    'Valle Fértil': ['Valle Fértil'].sort(),
    'Veinticinco de Mayo': ['Veinticinco de Mayo'].sort(),
    'Zonda': ['Zonda'].sort(),
  },

  'San Luis': {
    'Aymaraes': ['Tilisarao'].sort(),
    'Belgrano': ['Villa Mercedes'].sort(),
    'Capital': ['La Punta', 'San Luis'].sort(),
    'Chacabuco': ['Concarán', 'La Toma'].sort(),
    'Coronel Pringles': ['Naschel', 'San Francisco del Monte de Oro'].sort(),
    'General Pedernera': ['Buena Esperanza', 'Villa Mercedes'].sort(),
    'Gobernador Dupuy': ['Arizona', 'La Reforma'].sort(),
    'Junín': ['Juan Martín de Pueyrredón', 'Merlo'].sort(),
    'La Capital': ['Juana Koslay', 'La Punta', 'San Luis'].sort(),
    'Libertad': ['Quines'].sort(),
    'Pringles': ['Carpintería', 'Potrerillos de la Sierra'].sort(),
    'Totoral': ['Potrero de los Funes'].sort(),
  },

  'Santa Cruz': {
    'Corpen Aike': ['Puerto Santa Cruz', 'Río Gallegos'].sort(),
    'Deseado': ['Caleta Olivia', 'Las Heras', 'Puerto Deseado'].sort(),
    'Güer Aike': ['El Turbio', 'Río Gallegos', 'Río Turbio'].sort(),
    'Lago Argentino': ['El Calafate', 'El Chaltén'].sort(),
    'Lago Buenos Aires': ['Los Antiguos', 'Perito Moreno'].sort(),
    'Magallanes': ['Puerto San Julián'].sort(),
    'Río Chico': ['Gobernador Gregores', 'Tres Lagos'].sort(),
  },

  'Santa Fe': {
    'Belgrano': ['Armstrong', 'Las Parejas', 'Las Rosas', 'San Genaro'].sort(),
    'Caseros': ['Alcorta', 'Casilda', 'Firmat', 'Venado Tuerto', 'Wheelwright'].sort(),
    'Castellanos': ['Esperanza', 'Rafaela', 'San Jorge', 'Sunchales'].sort(),
    'Constitución': ['La Vanguardia', 'Villa Constitución'].sort(),
    'Garay': ['Helvecia', 'Malabrigo'].sort(),
    'General López': ['Firmat', 'Hughes', 'Rufino', 'Venado Tuerto'].sort(),
    'General Obligado': ['Reconquista', 'Tostado', 'Vera'].sort(),
    'Iriondo': ['Cañada de Gómez', 'Carcarañá', 'El Trébol', 'Gálvez'].sort(),
    'La Capital': ['Recreo', 'Santa Fe', 'Santo Tomé'].sort(),
    'Las Colonias': ['Esperanza', 'San Cristóbal', 'San Justo'].sort(),
    'Nueve de Julio': ['Tostado'].sort(),
    'Rosario': [
      'Capitán Bermúdez', 'Funes', 'Granadero Baigorria', 'Pérez',
      'Rosario', 'Villa Gobernador Gálvez',
    ].sort(),
    'San Cristóbal': ['Ceres', 'San Cristóbal', 'Tostado'].sort(),
    'San Javier': ['San Javier'].sort(),
    'San Jerónimo': ['Coronda', 'El Trébol', 'Gálvez', 'Laguna Paiva'].sort(),
    'San Justo': ['San Justo'].sort(),
    'San Lorenzo': ['Capitán Bermúdez', 'San Lorenzo'].sort(),
    'San Martín': ['Carlos Pellegrini', 'El Trébol'].sort(),
    'Vera': ['Malabrigo', 'Reconquista', 'Vera'].sort(),
  },

  'Santiago del Estero': {
    'Aguirre': ['Monte Quemado'].sort(),
    'Alberdi': ['Frías'].sort(),
    'Atamisqui': ['Villa Atamisqui'].sort(),
    'Avellaneda': ['Tintina'].sort(),
    'Banda': ['La Banda'].sort(),
    'Belgrano': ['Colonia Dora'].sort(),
    'Capital': ['Santiago del Estero'].sort(),
    'Choya': ['Frías'].sort(),
    'Copo': ['Monte Quemado'].sort(),
    'Figueroa': ['Garza'].sort(),
    'General Taboada': ['Añatuya', 'Bandera', 'Selva', 'Suncho Corral'].sort(),
    'Guasayán': ['Choya'].sort(),
    'Jiménez': ['Campo Gallo'].sort(),
    'Juan F. Ibarra': ['Nueva Esperanza'].sort(),
    'Loreto': ['Loreto'].sort(),
    'Mitre': ['Miraflores'].sort(),
    'Moreno': ['Quimilí'].sort(),
    'Ojo de Agua': ['Monte Quemado', 'Ojo de Agua'].sort(),
    'Pellegrini': ['Los Juríes'].sort(),
    'Río Hondo': ['Termas de Río Hondo'].sort(),
    'Rivadavia': ['Añatuya'].sort(),
    'Robles': ['La Banda'].sort(),
    'Salavina': ['Los Juríes'].sort(),
    'San Martín': ['Fernández'].sort(),
    'Sarmiento': ['Tintina'].sort(),
    'Silípica': ['Fernández'].sort(),
  },

  'Tierra del Fuego': {
    'Antártida e Islas del Atlántico Sur': ['Base Esperanza', 'Isla Soledad'].sort(),
    'Río Grande': ['Río Grande', 'Tolhuin'].sort(),
    'Ushuaia': ['Ushuaia'].sort(),
  },

  'Tucumán': {
    'Burruyacu': ['Burruyacú', 'Trancas'].sort(),
    'Capital': ['San Miguel de Tucumán'].sort(),
    'Chicligasta': ['Concepción', 'Monteros'].sort(),
    'Cruz Alta': ['Alderetes', 'Banda del Río Salí'].sort(),
    'Famaillá': ['Famaillá'].sort(),
    'Graneros': ['Graneros'].sort(),
    'Juan Bautista Alberdi': ['Juan Bautista Alberdi'].sort(),
    'La Cocha': ['La Cocha'].sort(),
    'Leales': ['Leales', 'Simoca'].sort(),
    'Lules': ['Lules', 'Manantial'].sort(),
    'Monteros': ['Aguilares', 'Monteros'].sort(),
    'Río Chico': ['Aguilares', 'Bella Vista'].sort(),
    'Tafí del Valle': ['Amaicha del Valle', 'Tafí del Valle'].sort(),
    'Tafí Viejo': ['El Cadillal', 'Tafí Viejo'].sort(),
    'Trancas': ['Trancas'].sort(),
    'Yerba Buena': ['Yerba Buena'].sort(),
  },
}
